CREATE TABLE IF NOT  EXISTS comment (
  id INT PRIMARY KEY AUTO_INCREMENT,
  content VARCHAR(1000)NOT NULL,
  -- 针对的动态id
  moment_id INT NOT NULL
  -- 谁发的评论 
  user_id INT NOT NULL,
  -- 评论的id
  comment_id INT DEFAULT NULL,

  FOREIGN KEY(moment_id) REFERENCES moment(id) ON DELETE CASCADE ON UPDATE CASCADE
  FOREIGN KEY(user_id) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE
  FOREIGN KEY(comment_id) REFERENCES comment(id) ON DELETE CASCADE ON UPDATE CASCADE
)
